export const PROFILE_SCREEN_HORIZONTAL_PADDING = 20;
export const PROFILE_SECTION_GAP = 28;
export const PROFILE_BLOCK_GAP = 18;
export const PROFILE_TITLE_FONT_SIZE = 34;
export const PROFILE_SETTINGS_SECTION_FONT_SIZE = 22;
