import {
  TAB_SCREEN_HORIZONTAL_PADDING,
  TAB_SCREEN_SECTION_GAP,
  TAB_SCREEN_SECTION_TITLE_FONT_SIZE,
} from '../../components/shared/tab-screen.constants';

export const PROFILE_SCREEN_HORIZONTAL_PADDING = TAB_SCREEN_HORIZONTAL_PADDING;
export const PROFILE_SECTION_GAP = TAB_SCREEN_SECTION_GAP;
export const PROFILE_BLOCK_GAP = 18;
export const PROFILE_SETTINGS_SECTION_FONT_SIZE = TAB_SCREEN_SECTION_TITLE_FONT_SIZE;

export const PROFILE_GUEST_HEADER_TOP_GAP = 8;
export const PROFILE_GUEST_SECTION_GAP = 12;
