/**
 * 🚨 Deze file wordt automatisch gegenereerd.
 * Bron: apps/cms/src/payload-types.ts
 * Voer "pnpm copy:payload-types" uit om te vernieuwen.
 */
/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    kiosks: Kiosk;
    markets: Market;
    taps: Tap;
    reviews: Review;
    requests: Request;
    wishes: Wish;
    notifications: Notification;
    follows: Follow;
    entitlements: Entitlement;
    reports: Report;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    kiosks: KiosksSelect<false> | KiosksSelect<true>;
    markets: MarketsSelect<false> | MarketsSelect<true>;
    taps: TapsSelect<false> | TapsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    requests: RequestsSelect<false> | RequestsSelect<true>;
    wishes: WishesSelect<false> | WishesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    follows: FollowsSelect<false> | FollowsSelect<true>;
    entitlements: EntitlementsSelect<false> | EntitlementsSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    mail: Mail;
    legal: Legal;
  };
  globalsSelect: {
    mail: MailSelect<false> | MailSelect<true>;
    legal: LegalSelect<false> | LegalSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      geocodeListings: TaskGeocodeListings;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Whether this is an anonymous user account
   */
  isAnonymous?: boolean | null;
  /**
   * Unique username for the user
   */
  username?: string | null;
  /**
   * First name
   */
  name?: string | null;
  /**
   * Last name
   */
  surname?: string | null;
  /**
   * Profile picture
   */
  avatar?: (number | null) | Media;
  /**
   * User role
   */
  role: 'user' | 'admin';
  signupOtpHash?: string | null;
  signupOtpExpiresAt?: string | null;
  /**
   * Google account subject identifier
   */
  googleSub?: string | null;
  /**
   * Expo push token voor dit account
   */
  pushToken?: string | null;
  /**
   * Laatst bijgewerkte push token
   */
  pushTokenUpdatedAt?: string | null;
  /**
   * User address information for claim validation
   */
  address?: {
    /**
     * Street name
     */
    street?: string | null;
    /**
     * House number
     */
    houseNumber?: string | null;
    /**
     * Postal code
     */
    postalCode?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * Geographic coordinates (optional)
     *
     * @minItems 2
     * @maxItems 2
     */
    coordinates?: [number, number] | null;
    /**
     * Canonical latitude derived from coordinates
     */
    latitude?: number | null;
    /**
     * Canonical longitude derived from coordinates
     */
    longitude?: number | null;
  };
  /**
   * User's favorite places
   */
  favorites?:
    | {
        place:
          | {
              relationTo: 'kiosks';
              value: number | Kiosk;
            }
          | {
              relationTo: 'markets';
              value: number | Market;
            }
          | {
              relationTo: 'taps';
              value: number | Tap;
            };
        id?: string | null;
      }[]
    | null;
  /**
   * Voorkeuren voor push notificaties
   */
  notificationSettings?: {
    photoRequests?: boolean | null;
    statusUpdates?: boolean | null;
    reviews?: boolean | null;
    favorites?: boolean | null;
  };
  /**
   * One-time unlocked search scopes for listings
   */
  searchAccess?: {
    province?: boolean | null;
    country?: boolean | null;
    world?: boolean | null;
  };
  /**
   * Default home search area for entitlement checks
   */
  homeArea?: {
    city?: string | null;
    province?: string | null;
    country?: string | null;
    radiusMeters?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kiosks".
 */
export interface Kiosk {
  id: number;
  name: string;
  description: string;
  kioskSubtype: 'books' | 'hygiene' | 'community' | 'other';
  publishStatus: 'draft' | 'live';
  /**
   * Soft delete: set to hide from public map and search; clear to restore. Owners use the app or PATCH; hard remove is admin-only.
   */
  deletedAt?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Owner account for this kiosk
   */
  owner?: (number | null) | User;
  /**
   * User who has submitted a claim for this place
   */
  pendingOwner?: (number | null) | User;
  location?: {
    street?: string | null;
    houseNumber?: string | null;
    zipCode?: string | null;
    city?: string | null;
    province?: string | null;
    country?: string | null;
    /**
     * Full address string for display and geocoding
     */
    address?: string | null;
    /**
     * @minItems 2
     * @maxItems 2
     */
    coordinates?: [number, number] | null;
    /**
     * Canonical latitude for cross-database geo querying
     */
    latitude?: number | null;
    /**
     * Canonical longitude for cross-database geo querying
     */
    longitude?: number | null;
  };
  facilities?: {
    openingHours?: string | null;
    facilities?:
      | {
          facility?:
            | (
                | '24_7_access'
                | 'wheelchair_accessible'
                | 'parking'
                | 'indoor'
                | 'outdoor'
                | 'sheltered'
                | 'lighting'
                | 'security_camera'
                | 'contact_required'
                | 'free_access'
                | 'membership_required'
              )
            | null;
          id?: string | null;
        }[]
      | null;
    rules?: string | null;
    contactInfo?: string | null;
  };
  pictures?:
    | {
        photo: number | Media;
        created_by: number | User;
        status: 'pending' | 'approved' | 'rejected';
        approved_by?: (number | null) | User;
        approved_at?: string | null;
        rejection_reason?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets".
 */
export interface Market {
  id: number;
  name: string;
  description: string;
  marketSubtype: 'honey' | 'milk' | 'meat' | 'vegetables' | 'other';
  publishStatus: 'draft' | 'live';
  /**
   * Soft delete: set to hide from public map and search; clear to restore. Owners use the app or PATCH; hard remove is admin-only.
   */
  deletedAt?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Owner account for this market
   */
  owner?: (number | null) | User;
  /**
   * User who has submitted a claim for this place
   */
  pendingOwner?: (number | null) | User;
  location?: {
    street?: string | null;
    houseNumber?: string | null;
    zipCode?: string | null;
    city?: string | null;
    province?: string | null;
    country?: string | null;
    /**
     * Full address string for display and geocoding
     */
    address?: string | null;
    /**
     * @minItems 2
     * @maxItems 2
     */
    coordinates?: [number, number] | null;
    /**
     * Canonical latitude for cross-database geo querying
     */
    latitude?: number | null;
    /**
     * Canonical longitude for cross-database geo querying
     */
    longitude?: number | null;
  };
  facilities?: {
    openingHours?: string | null;
    facilities?:
      | {
          facility?:
            | (
                | '24_7_access'
                | 'wheelchair_accessible'
                | 'parking'
                | 'indoor'
                | 'outdoor'
                | 'sheltered'
                | 'lighting'
                | 'security_camera'
                | 'contact_required'
                | 'free_access'
                | 'membership_required'
              )
            | null;
          id?: string | null;
        }[]
      | null;
    rules?: string | null;
    contactInfo?: string | null;
  };
  pictures?:
    | {
        photo: number | Media;
        created_by: number | User;
        status: 'pending' | 'approved' | 'rejected';
        approved_by?: (number | null) | User;
        approved_at?: string | null;
        rejection_reason?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taps".
 */
export interface Tap {
  id: number;
  name: string;
  description: string;
  tapSubtype: 'indoor' | 'outdoor';
  publishStatus: 'draft' | 'live';
  /**
   * Soft delete: set to hide from public map and search; clear to restore. Owners use the app or PATCH; hard remove is admin-only.
   */
  deletedAt?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Owner account for this tap
   */
  owner?: (number | null) | User;
  /**
   * User who has submitted a claim for this place
   */
  pendingOwner?: (number | null) | User;
  location?: {
    street?: string | null;
    houseNumber?: string | null;
    zipCode?: string | null;
    city?: string | null;
    province?: string | null;
    country?: string | null;
    /**
     * Full address string for display and geocoding
     */
    address?: string | null;
    /**
     * @minItems 2
     * @maxItems 2
     */
    coordinates?: [number, number] | null;
    /**
     * Canonical latitude for cross-database geo querying
     */
    latitude?: number | null;
    /**
     * Canonical longitude for cross-database geo querying
     */
    longitude?: number | null;
  };
  facilities?: {
    openingHours?: string | null;
    facilities?:
      | {
          facility?:
            | (
                | '24_7_access'
                | 'wheelchair_accessible'
                | 'parking'
                | 'indoor'
                | 'outdoor'
                | 'sheltered'
                | 'lighting'
                | 'security_camera'
                | 'contact_required'
                | 'free_access'
                | 'membership_required'
              )
            | null;
          id?: string | null;
        }[]
      | null;
    rules?: string | null;
    contactInfo?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  rating: number;
  description: string;
  photos?:
    | {
        photo: number | Media;
        id?: string | null;
      }[]
    | null;
  created_by: number | User;
  place:
    | {
        relationTo: 'kiosks';
        value: number | Kiosk;
      }
    | {
        relationTo: 'markets';
        value: number | Market;
      }
    | {
        relationTo: 'taps';
        value: number | Tap;
      };
  status: 'published' | 'hidden';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requests".
 */
export interface Request {
  id: number;
  /**
   * The place being claimed
   */
  place:
    | {
        relationTo: 'kiosks';
        value: number | Kiosk;
      }
    | {
        relationTo: 'markets';
        value: number | Market;
      }
    | {
        relationTo: 'taps';
        value: number | Tap;
      };
  /**
   * User submitting the claim
   */
  user: number | User;
  /**
   * Claim status
   */
  status: 'pending' | 'under_review' | 'approved' | 'rejected';
  /**
   * Distance in meters from user location to place (for auto-approval)
   */
  distanceMeters?: number | null;
  /**
   * Snapshot of user address at time of claim
   */
  addressSnapshot?: {
    street?: string | null;
    houseNumber?: string | null;
    postalCode?: string | null;
    city?: string | null;
    /**
     * @minItems 2
     * @maxItems 2
     */
    coordinates?: [number, number] | null;
    latitude?: number | null;
    longitude?: number | null;
  };
  /**
   * Additional notes from the user or admin
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishes".
 */
export interface Wish {
  id: number;
  /**
   * What are you looking for? (e.g., "Tampons", "The Great Gatsby", "Drill")
   */
  title: string;
  /**
   * What type of item is this?
   */
  category?: ('book' | 'hygiene' | 'tool' | 'food' | 'clothing' | 'other') | null;
  /**
   * Author name (for books)
   */
  author?: string | null;
  /**
   * ISBN number (for books)
   */
  isbn?: string | null;
  /**
   * Brand or manufacturer (optional)
   */
  brand?: string | null;
  /**
   * Additional details about what you're looking for
   */
  description?: string | null;
  status: 'active' | 'fulfilled' | 'archived';
  location: {
    latitude: number;
    longitude: number;
    /**
     * Notification radius in kilometers
     */
    radius: number;
    /**
     * Canonical radius in meters
     */
    radiusMeters?: number | null;
  };
  created_by: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  /**
   * User who receives this notification
   */
  user: number | User;
  /**
   * Type of notification
   */
  type:
    | 'photo_request'
    | 'photo_approved'
    | 'photo_rejected'
    | 'review'
    | 'favorite'
    | 'claim_approved'
    | 'claim_rejected'
    | 'new_follower'
    | 'area_match'
    | 'report_update'
    | 'system';
  /**
   * Notification title
   */
  title: string;
  /**
   * Notification message body
   */
  message: string;
  /**
   * Whether user has read this notification
   */
  read?: boolean | null;
  /**
   * Additional data (IDs, URLs, etc.) for deep linking
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Deep link URL for mobile app (e.g., deelbaar://listing/123)
   */
  actionUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "follows".
 */
export interface Follow {
  id: number;
  user: number | User;
  targetType: 'place' | 'area';
  place?:
    | ({
        relationTo: 'kiosks';
        value: number | Kiosk;
      } | null)
    | ({
        relationTo: 'markets';
        value: number | Market;
      } | null)
    | ({
        relationTo: 'taps';
        value: number | Tap;
      } | null);
  area?: {
    name?: string | null;
    latitude?: number | null;
    longitude?: number | null;
    radiusMeters?: number | null;
  };
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entitlements".
 */
export interface Entitlement {
  id: number;
  user: number | User;
  scope: 'city' | 'province' | 'country' | 'world';
  status: 'active' | 'expired' | 'revoked';
  source: string;
  /**
   * Optional expiration. Empty means no expiry.
   */
  expiresAt?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: number;
  targetType: 'place' | 'review';
  place?:
    | ({
        relationTo: 'kiosks';
        value: number | Kiosk;
      } | null)
    | ({
        relationTo: 'markets';
        value: number | Market;
      } | null)
    | ({
        relationTo: 'taps';
        value: number | Tap;
      } | null);
  review?: (number | null) | Review;
  reason: 'spam' | 'offensive' | 'misleading' | 'unsafe' | 'other';
  details?: string | null;
  status: 'open' | 'in_review' | 'resolved' | 'dismissed';
  createdBy: number | User;
  reviewedBy?: (number | null) | User;
  resolutionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'geocodeListings';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'geocodeListings') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'kiosks';
        value: number | Kiosk;
      } | null)
    | ({
        relationTo: 'markets';
        value: number | Market;
      } | null)
    | ({
        relationTo: 'taps';
        value: number | Tap;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'requests';
        value: number | Request;
      } | null)
    | ({
        relationTo: 'wishes';
        value: number | Wish;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'follows';
        value: number | Follow;
      } | null)
    | ({
        relationTo: 'entitlements';
        value: number | Entitlement;
      } | null)
    | ({
        relationTo: 'reports';
        value: number | Report;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  isAnonymous?: T;
  username?: T;
  name?: T;
  surname?: T;
  avatar?: T;
  role?: T;
  signupOtpHash?: T;
  signupOtpExpiresAt?: T;
  googleSub?: T;
  pushToken?: T;
  pushTokenUpdatedAt?: T;
  address?:
    | T
    | {
        street?: T;
        houseNumber?: T;
        postalCode?: T;
        city?: T;
        coordinates?: T;
        latitude?: T;
        longitude?: T;
      };
  favorites?:
    | T
    | {
        place?: T;
        id?: T;
      };
  notificationSettings?:
    | T
    | {
        photoRequests?: T;
        statusUpdates?: T;
        reviews?: T;
        favorites?: T;
      };
  searchAccess?:
    | T
    | {
        province?: T;
        country?: T;
        world?: T;
      };
  homeArea?:
    | T
    | {
        city?: T;
        province?: T;
        country?: T;
        radiusMeters?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kiosks_select".
 */
export interface KiosksSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  kioskSubtype?: T;
  publishStatus?: T;
  deletedAt?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  owner?: T;
  pendingOwner?: T;
  location?:
    | T
    | {
        street?: T;
        houseNumber?: T;
        zipCode?: T;
        city?: T;
        province?: T;
        country?: T;
        address?: T;
        coordinates?: T;
        latitude?: T;
        longitude?: T;
      };
  facilities?:
    | T
    | {
        openingHours?: T;
        facilities?:
          | T
          | {
              facility?: T;
              id?: T;
            };
        rules?: T;
        contactInfo?: T;
      };
  pictures?:
    | T
    | {
        photo?: T;
        created_by?: T;
        status?: T;
        approved_by?: T;
        approved_at?: T;
        rejection_reason?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets_select".
 */
export interface MarketsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  marketSubtype?: T;
  publishStatus?: T;
  deletedAt?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  owner?: T;
  pendingOwner?: T;
  location?:
    | T
    | {
        street?: T;
        houseNumber?: T;
        zipCode?: T;
        city?: T;
        province?: T;
        country?: T;
        address?: T;
        coordinates?: T;
        latitude?: T;
        longitude?: T;
      };
  facilities?:
    | T
    | {
        openingHours?: T;
        facilities?:
          | T
          | {
              facility?: T;
              id?: T;
            };
        rules?: T;
        contactInfo?: T;
      };
  pictures?:
    | T
    | {
        photo?: T;
        created_by?: T;
        status?: T;
        approved_by?: T;
        approved_at?: T;
        rejection_reason?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taps_select".
 */
export interface TapsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  tapSubtype?: T;
  publishStatus?: T;
  deletedAt?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  owner?: T;
  pendingOwner?: T;
  location?:
    | T
    | {
        street?: T;
        houseNumber?: T;
        zipCode?: T;
        city?: T;
        province?: T;
        country?: T;
        address?: T;
        coordinates?: T;
        latitude?: T;
        longitude?: T;
      };
  facilities?:
    | T
    | {
        openingHours?: T;
        facilities?:
          | T
          | {
              facility?: T;
              id?: T;
            };
        rules?: T;
        contactInfo?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  rating?: T;
  description?: T;
  photos?:
    | T
    | {
        photo?: T;
        id?: T;
      };
  created_by?: T;
  place?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requests_select".
 */
export interface RequestsSelect<T extends boolean = true> {
  place?: T;
  user?: T;
  status?: T;
  distanceMeters?: T;
  addressSnapshot?:
    | T
    | {
        street?: T;
        houseNumber?: T;
        postalCode?: T;
        city?: T;
        coordinates?: T;
        latitude?: T;
        longitude?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishes_select".
 */
export interface WishesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  author?: T;
  isbn?: T;
  brand?: T;
  description?: T;
  status?: T;
  location?:
    | T
    | {
        latitude?: T;
        longitude?: T;
        radius?: T;
        radiusMeters?: T;
      };
  created_by?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  title?: T;
  message?: T;
  read?: T;
  data?: T;
  actionUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "follows_select".
 */
export interface FollowsSelect<T extends boolean = true> {
  user?: T;
  targetType?: T;
  place?: T;
  area?:
    | T
    | {
        name?: T;
        latitude?: T;
        longitude?: T;
        radiusMeters?: T;
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entitlements_select".
 */
export interface EntitlementsSelect<T extends boolean = true> {
  user?: T;
  scope?: T;
  status?: T;
  source?: T;
  expiresAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  targetType?: T;
  place?: T;
  review?: T;
  reason?: T;
  details?: T;
  status?: T;
  createdBy?: T;
  reviewedBy?: T;
  resolutionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail".
 */
export interface Mail {
  id: number;
  headerLogo: number | Media;
  footerLogo: number | Media;
  businessEmail: string;
  verify?: {
    /**
     * Gebruik de volgende placeholders om dynamische waarden in te voegen: {{userName}}, {{verificationUrl}}
     */
    subject?: string | null;
    /**
     * Gebruik de volgende placeholders om dynamische waarden in te voegen: {{userName}}, {{verificationUrl}}
     */
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  forgotPassword?: {
    /**
     * Gebruik de volgende placeholders om dynamische waarden in te voegen: {{userName}}, {{resetUrl}}
     */
    subject?: string | null;
    /**
     * Gebruik de volgende placeholders om dynamische waarden in te voegen: {{userName}}, {{resetUrl}}
     */
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal".
 */
export interface Legal {
  id: number;
  terms: {
    title: string;
    body: string;
  };
  privacy: {
    title: string;
    body: string;
  };
  about: {
    title: string;
    body: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail_select".
 */
export interface MailSelect<T extends boolean = true> {
  headerLogo?: T;
  footerLogo?: T;
  businessEmail?: T;
  verify?:
    | T
    | {
        subject?: T;
        content?: T;
      };
  forgotPassword?:
    | T
    | {
        subject?: T;
        content?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal_select".
 */
export interface LegalSelect<T extends boolean = true> {
  terms?:
    | T
    | {
        title?: T;
        body?: T;
      };
  privacy?:
    | T
    | {
        title?: T;
        body?: T;
      };
  about?:
    | T
    | {
        title?: T;
        body?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGeocodeListings".
 */
export interface TaskGeocodeListings {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
