/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    listings: Listing;
    reviews: Review;
    requests: Request;
    wishes: Wish;
    notifications: Notification;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    listings: ListingsSelect<false> | ListingsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    requests: RequestsSelect<false> | RequestsSelect<true>;
    wishes: WishesSelect<false> | WishesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    mail: Mail;
  };
  globalsSelect: {
    mail: MailSelect<false> | MailSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      geocodeListings: TaskGeocodeListings;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Whether this is an anonymous user account
   */
  isAnonymous?: boolean | null;
  /**
   * Unique username for the user
   */
  username?: string | null;
  /**
   * First name
   */
  name?: string | null;
  /**
   * Last name
   */
  surname?: string | null;
  /**
   * Profile picture
   */
  avatar?: (string | null) | Media;
  /**
   * User role
   */
  role: 'user' | 'admin';
  /**
   * Google account subject identifier
   */
  googleSub?: string | null;
  /**
   * Expo push token voor dit account
   */
  pushToken?: string | null;
  /**
   * Laatst bijgewerkte push token
   */
  pushTokenUpdatedAt?: string | null;
  /**
   * User address information for claim validation
   */
  address?: {
    /**
     * Street name
     */
    street?: string | null;
    /**
     * House number
     */
    houseNumber?: string | null;
    /**
     * Postal code
     */
    postalCode?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * Geographic coordinates (optional)
     *
     * @minItems 2
     * @maxItems 2
     */
    coordinates?: [number, number] | null;
  };
  /**
   * User's favorite listings
   */
  favorites?:
    | {
        listing: string | Listing;
        id?: string | null;
      }[]
    | null;
  /**
   * Voorkeuren voor push notificaties
   */
  notificationSettings?: {
    photoRequests?: boolean | null;
    statusUpdates?: boolean | null;
    reviews?: boolean | null;
    favorites?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: string;
  name: string;
  description: string;
  category: 'book' | 'food' | 'hygiene' | 'community' | 'farm' | 'other';
  /**
   * Whether this listing is visible to the public or still in draft mode
   */
  publishStatus: 'draft' | 'live';
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The user who owns this listing
   */
  owner?: (string | null) | User;
  /**
   * User who has submitted a claim for this listing
   */
  pendingOwner?: (string | null) | User;
  location?: {
    street?: string | null;
    houseNumber?: string | null;
    zipCode?: string | null;
    city?: string | null;
    province?: string | null;
    country?: string | null;
    /**
     * Full address string for display and geocoding
     */
    address?: string | null;
    /**
     * @minItems 2
     * @maxItems 2
     */
    coordinates?: [number, number] | null;
  };
  facilities?: {
    /**
     * When is this location accessible? E.g., "Mon-Fri 9-17, Sat 10-16"
     */
    openingHours?: string | null;
    facilities?:
      | {
          facility?:
            | (
                | '24_7_access'
                | 'wheelchair_accessible'
                | 'parking'
                | 'indoor'
                | 'outdoor'
                | 'sheltered'
                | 'lighting'
                | 'security_camera'
                | 'contact_required'
                | 'free_access'
                | 'membership_required'
              )
            | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Any special rules or guidelines for using this location
     */
    rules?: string | null;
    /**
     * How can people get in touch if they need help?
     */
    contactInfo?: string | null;
  };
  /**
   * Photos for this listing
   */
  pictures?:
    | {
        photo: string | Media;
        created_by: string | User;
        status: 'pending' | 'approved' | 'rejected';
        approved_by?: (string | null) | User;
        approved_at?: string | null;
        rejection_reason?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  rating: number;
  description: string;
  created_by: string | User;
  listing: string | Listing;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requests".
 */
export interface Request {
  id: string;
  /**
   * The listing being claimed
   */
  listing: string | Listing;
  /**
   * User submitting the claim
   */
  user: string | User;
  /**
   * Claim status
   */
  status: 'pending' | 'approved' | 'rejected';
  /**
   * Distance in meters from user location to listing (for auto-approval)
   */
  distanceMeters?: number | null;
  /**
   * Snapshot of user address at time of claim
   */
  addressSnapshot?: {
    street?: string | null;
    houseNumber?: string | null;
    postalCode?: string | null;
    city?: string | null;
    /**
     * @minItems 2
     * @maxItems 2
     */
    coordinates?: [number, number] | null;
  };
  /**
   * Additional notes from the user or admin
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishes".
 */
export interface Wish {
  id: string;
  /**
   * What are you looking for? (e.g., "Tampons", "The Great Gatsby", "Drill")
   */
  title: string;
  /**
   * What type of item is this?
   */
  category?: ('book' | 'hygiene' | 'tool' | 'food' | 'clothing' | 'other') | null;
  /**
   * Author name (for books)
   */
  author?: string | null;
  /**
   * ISBN number (for books)
   */
  isbn?: string | null;
  /**
   * Brand or manufacturer (optional)
   */
  brand?: string | null;
  /**
   * Additional details about what you're looking for
   */
  description?: string | null;
  location: {
    latitude: number;
    longitude: number;
    /**
     * Notification radius in kilometers
     */
    radius: number;
  };
  created_by: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  /**
   * User who receives this notification
   */
  user: string | User;
  /**
   * Type of notification
   */
  type:
    | 'photo_request'
    | 'photo_approved'
    | 'photo_rejected'
    | 'review'
    | 'favorite'
    | 'claim_approved'
    | 'claim_rejected'
    | 'system';
  /**
   * Notification title
   */
  title: string;
  /**
   * Notification message body
   */
  message: string;
  /**
   * Whether user has read this notification
   */
  read?: boolean | null;
  /**
   * Additional data (IDs, URLs, etc.) for deep linking
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Deep link URL for mobile app (e.g., deelbaar://listing/123)
   */
  actionUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'geocodeListings';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'geocodeListings') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'listings';
        value: string | Listing;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'requests';
        value: string | Request;
      } | null)
    | ({
        relationTo: 'wishes';
        value: string | Wish;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  isAnonymous?: T;
  username?: T;
  name?: T;
  surname?: T;
  avatar?: T;
  role?: T;
  googleSub?: T;
  pushToken?: T;
  pushTokenUpdatedAt?: T;
  address?:
    | T
    | {
        street?: T;
        houseNumber?: T;
        postalCode?: T;
        city?: T;
        coordinates?: T;
      };
  favorites?:
    | T
    | {
        listing?: T;
        id?: T;
      };
  notificationSettings?:
    | T
    | {
        photoRequests?: T;
        statusUpdates?: T;
        reviews?: T;
        favorites?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings_select".
 */
export interface ListingsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  category?: T;
  publishStatus?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  owner?: T;
  pendingOwner?: T;
  location?:
    | T
    | {
        street?: T;
        houseNumber?: T;
        zipCode?: T;
        city?: T;
        province?: T;
        country?: T;
        address?: T;
        coordinates?: T;
      };
  facilities?:
    | T
    | {
        openingHours?: T;
        facilities?:
          | T
          | {
              facility?: T;
              id?: T;
            };
        rules?: T;
        contactInfo?: T;
      };
  pictures?:
    | T
    | {
        photo?: T;
        created_by?: T;
        status?: T;
        approved_by?: T;
        approved_at?: T;
        rejection_reason?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  rating?: T;
  description?: T;
  created_by?: T;
  listing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requests_select".
 */
export interface RequestsSelect<T extends boolean = true> {
  listing?: T;
  user?: T;
  status?: T;
  distanceMeters?: T;
  addressSnapshot?:
    | T
    | {
        street?: T;
        houseNumber?: T;
        postalCode?: T;
        city?: T;
        coordinates?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishes_select".
 */
export interface WishesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  author?: T;
  isbn?: T;
  brand?: T;
  description?: T;
  location?:
    | T
    | {
        latitude?: T;
        longitude?: T;
        radius?: T;
      };
  created_by?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  title?: T;
  message?: T;
  read?: T;
  data?: T;
  actionUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail".
 */
export interface Mail {
  id: string;
  headerLogo: string | Media;
  footerLogo: string | Media;
  businessEmail: string;
  verify?: {
    /**
     * Gebruik de volgende placeholders om dynamische waarden in te voegen: {{userName}}, {{verificationUrl}}
     */
    subject?: string | null;
    /**
     * Gebruik de volgende placeholders om dynamische waarden in te voegen: {{userName}}, {{verificationUrl}}
     */
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  forgotPassword?: {
    /**
     * Gebruik de volgende placeholders om dynamische waarden in te voegen: {{userName}}, {{resetUrl}}
     */
    subject?: string | null;
    /**
     * Gebruik de volgende placeholders om dynamische waarden in te voegen: {{userName}}, {{resetUrl}}
     */
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail_select".
 */
export interface MailSelect<T extends boolean = true> {
  headerLogo?: T;
  footerLogo?: T;
  businessEmail?: T;
  verify?:
    | T
    | {
        subject?: T;
        content?: T;
      };
  forgotPassword?:
    | T
    | {
        subject?: T;
        content?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGeocodeListings".
 */
export interface TaskGeocodeListings {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
