export const TAB_SCREEN_HORIZONTAL_PADDING = 16;
export const TAB_SCREEN_HEADER_TOP_GAP = 16;
export const TAB_SCREEN_SECTION_GAP = 24;
export const TAB_SCREEN_CONTENT_BOTTOM_PADDING = 16;
export const TAB_SCREEN_TITLE_FONT_SIZE = 28;
export const TAB_SCREEN_TITLE_LINE_HEIGHT = 34;
export const TAB_SCREEN_SECTION_TITLE_FONT_SIZE = 22;
