#name: Android App APK Build
#
#on:
#  pull_request:
#    branches:
#      - develop
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Setup repo
#        uses: actions/checkout@v4
#
#      - name: Setup node
#        uses: actions/setup-node@v4
#        with:
#          node-version: 18.x
#          cache: 'yarn'
#          cache-dependency-path: 'yarn.lock'
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#
#      - name: Setup Android SDK
#        uses: android-actions/setup-android@v3
#
#      - name: Setup Expo
#        uses: expo/expo-github-action@v8
#        with:
#          expo-version: latest
#          eas-version: latest
#          token: ${{ secrets.EXPO_TOKEN }}
#
#      - name: Install dependencies
#        run: yarn install
#
#      - name: Build Android app
#        run: eas build --platform android --profile development --local --output ${{ github.workspace }}/app-development.apk
#
#      - name: Upload APK artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: app-development
#          path: ${{ github.workspace }}/app-development.apk