name: iOS App Simulator Build

on:
  workflow_dispatch:
  # Trigger for manual build

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Build iOS app for Simulator
        run: eas build --platform ios --profile preview --local --non-interactive --output ${{ github.workspace }}/app-preview.app

      - name: Upload iOS simulator artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-simulator
          path: ${{ github.workspace }}/app-preview.app
