name: Publish Pull Request
on:
  pull_request:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'yarn'  # Cache `yarn` dependencies to speed up subsequent runs

      - name: Install Dependencies
        run: yarn

      - name: Publish to Expo Go
        env:
          NODE_ENV: dev
        run: npx expo publish --non-interactive --release-channel pr-${{ github.event.number }}
        continue-on-error: true  # Allows the workflow to continue even if this step fails

      - name: Handle Publish Failure
        if: failure()
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            🚨 **Expo Publish Failed**
            Please check the workflow logs for more details on why the publish step failed.

      - name: Add Expo Link to PR
        if: success()
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            ## Test this PR with Expo Go
            ![Expo QR](https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=exp://exp.host/@iepsma/deelbaar?release-channel=pr-${{ github.event.number }})
            **------ Build published to [Expo](https://exp.host/@iepsma/deelbaar?release-channel=pr-${{ github.event.number }}) ------**
